# Site
name: "Events – Rotaract 3190"
description: "Listing Events and Projects in Rotaract District 3190"
meta_description: "Listing Events and Projects in Rotaract District 3190"
logo: '/assets/images/logo.png'
favicon: '/assets/images/logo.png'
og_img: '/assets/images/black_og.png'
default_club_logo: '/assets/images/rotarywheel.jpg'
baseurl: ""
url: "https://events.rotaract3190.org"
google_analytics: 'UA-122171689-3'
# disqus: 'rotaract3190'
mailchimp-list: 'https://rotaract3190.us19.list-manage.com/subscribe/post?u=ec2994fa04b0856e3913be84e&amp;id=7eb0482b27'

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    category: '/:name/'
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/clubs/:name/'
    
# Pagination 
paginate: 9
paginate_path: /page:num/
    
# Other
markdown: kramdown
permalink: /:year/:month/:day/:title/
highlighter: rouge

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

include:
  - _redirects
