# Site
name: "Events – Rotaract 3190"
description: "Listing Events and Projects in Rotaract District 3190"
meta_description: "Listing Events and Projects in Rotaract District 3190"
logo: '/assets/images/logo.png'
favicon: '/assets/images/logo.png'
og_img: '/assets/images/black_og.png'
baseurl: ""
url: "https://events.rotaract3190.org"
google_analytics: 'UA-122171689-3'
# disqus: 'rotaract3190'
mailchimp-list: 'https://rotaract3190.us19.list-manage.com/subscribe/post?u=ec2994fa04b0856e3913be84e&amp;id=7eb0482b27'

# Authors
authors:
  rcbsw:
    name: RCSBW
    display_name: Rotaract Club of Bangalore Southwest
    gravatar: 
    email: 
    web: 
    twitter: https://www.facebook.com/RCBSW/
    description: "Rotaract Club of Bangalore Southwest"
  rcgems:
    name: RCGEMS
    display_name: Rotaract Club of Gems B School
    gravatar: 
    email: 
    web: 
    twitter: https://www.facebook.com/Rotaract-Club-Of-Gems-B-School-RID-3190-1659414430758514/
    description: "Rotaract Club of Gems B School"

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    category: '/:name/'
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/clubs/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown
permalink: /:year/:month/:day/:title/
highlighter: rouge